version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1042"

      ALGAFOOD.STORAGE.S3.CHAVE-ACESSO-SECRETA: "6C4hLgEJJ32TfqRdaFcediyEcrXNXN0LNVBuva5h"
      ALGAFOOD.STORAGE.S3.ID-CHAVE-ACESSO: "AKIA33MIL5MN45PQBFRS"
    ports:
      - "3306:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    command: ["/wait-for-it.sh", "algafodd-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api