version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1042"
      algafood.storage.s3.chave-acesso-secreta: "6C4hLgEJJ32TfqRdaFcediyEcrXNXN0LNVBuva5h"
      algafood.storage.s3.id-chave-acesso: "AKIA33MIL5MN45PQBFRS"
    ports:
      - "3306:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
    environment:
      DB_HOST: algafood-mysql
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql